---
application:
  name: "umami"
  project: "umami"
  organization: "QoveryCommunity"
  storage:
  - name: "umami"
    size: "30"
    type: "ssd"
    mount_point: "/mnt/umami"
databases:
- type: "POSTGRESQL"
  name: "umami-dy"
  version: "11"
routers:
- name: "main-umami"
  routes:
  - application_name: "umami"
    paths:
    - "/*"
